export const projects = [
    {
    id: 1,
    title: "My Portfolio",
    description:"A personal portfolio website showcasing my skills, projects, and experience.",
    image: "/next/portfolio.PNG",
    technologies: [
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "JavaScript",
      "Animation",
      "Next.js",
    ],
    demoUrl: "https://new-portfolio-fawn-xi.vercel.app/",
    codeUrl: "https://github.com/MohamedElrewiny/New-Portfolio",
  },
  {
    id: 2,
    title: "Fresh Cart",
    description:
      "A full-featured e-commerce platform with product listings, cart functionality, and payment integration.",
    image: "/react/e-commerce.PNG",
    technologies: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "JavaScript",
      "React",
      "context API",
      "React Library",
    ],
    demoUrl: "https://mohamedelrewiny.github.io/Fresh-Cart/",
    codeUrl: "https://github.com/MohamedElrewiny/Fresh-Cart",
  },
  {
    id: 3,
    title: "VEHEX",
    description:
      "Auto parts website, car maintenance and oil change for most car brands.",
    image: "/react/vehex.png",
    technologies: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "JavaScript",
      "Swiper",
      "React",
      "context API",
      "React Library",
    ],
    demoUrl: "https://mohamedelrewiny.github.io/VEHEX/",
    codeUrl: "https://github.com/MohamedElrewiny/VEHEX",
  },
  {
    id: 4,
    title: "Saqralmadina",
    description:
      "A site for trips and transportation within the Kingdom of Saudi Arabia.",
    image: "/js/saqr.PNG",
    technologies: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "JavaScript",
      "Swiper",
      "jQuery",
      "WOW",
    ],
    demoUrl: "https://saqralmadina.com/",
    codeUrl:
      "https://github.com/MohamedElrewiny/saqralmadina?tab=readme-ov-file",
  },
  {
    id: 5,
    title: "La case de los regalos",
    description:
      "Spanish Commercial site selling perfumes, cosmetics and gifts.",
    image: "/css/spanish.PNG",
    technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "Swiper"],
    demoUrl: "https://lacasa-delosregalos.com/",
    codeUrl:
      "https://github.com/MohamedElrewiny/Spanish-Ecommerce?tab=readme-ov-file",
  },
  {
    id: 6,
    title: "Yummy",
    description: "display foods of different types, countries.",
    image: "/js/yummy.PNG",
    technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript", "jQuery"],
    demoUrl: "https://mohamedelrewiny.github.io/Yummy/",
    codeUrl: "https://github.com/MohamedElrewiny/Yummy?tab=readme-ov-file",
  },
  {
    id: 7,
    title: "The weather",
    description:
      "display the weather conditions in more than one place around the world.",
    image: "/js/weather.PNG",
    technologies: ["HTML5", "CSS3", "Bootstrap", "JavaScript"],
    demoUrl: "https://mohamedelrewiny.github.io/weather-/",
    codeUrl: "https://github.com/MohamedElrewiny/weather-?tab=readme-ov-file",
  },
  {
    id: 8,
    title: "Quiz App",
    description:
      "Electronic questions system (tests) at a specific time and at the end the result is displayed.",
    image: "/js/quiz.PNG",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    demoUrl: "https://mohamedelrewiny.github.io/Quiz-App/",
    codeUrl: "https://github.com/MohamedElrewiny/Quiz-App?tab=readme-ov-file",
  },
  {
    id: 9,
    title: "Routing Test",
    description: "Routing for Testing.",
    image: "/react/task.PNG",
    technologies: ["HTML5", "CSS3", "JavaScript", "React"],
    demoUrl: "https://mohamedelrewiny.github.io/routingReactTask/#/home",
    codeUrl: "https://github.com/MohamedElrewiny/routingReactTask",
  },
  {
    id: 10,
    title: "Special Design",
    description: "Special Design for Testing.",
    image: "/css/specialDesign.PNG",
    technologies: ["HTML5", "CSS3"],
    demoUrl: "https://mohamedelrewiny.github.io/special-design/",
    codeUrl:
      "https://github.com/MohamedElrewiny/special-design?tab=readme-ov-file",
  },
  {
    id: 11,
    title: "cup-of-Tea-Animation",
    description:
      "                Animated Hot Cup of Tea using Html & CSS only | CSS Animation Effects.",
    image: "/css/cup-tea.png",
    technologies: ["HTML5", "CSS3", "Animation"],
    demoUrl: "https://mohamedelrewiny.github.io/cup-of-Tea-Animation/",
    codeUrl: "https://github.com/MohamedElrewiny/cup-of-Tea-Animation",
  },
  {
    id: 12,
    title: "Gymster",
    description: "Gymster for Testing.",
    image: "/css/gymster.PNG",
    technologies: ["HTML5", "CSS3"],
    demoUrl: "https://mohamedelrewiny.github.io/GYMSTER/",
    codeUrl: "https://github.com/MohamedElrewiny/GYMSTER?tab=readme-ov-file",
  },
  {
    id: 13,
    title: "cafeHouse",
    description: "cafeHouse for Testing.",
    image: "/css/cafe.PNG",
    technologies: ["HTML5", "CSS3"],
    demoUrl: "https://mohamedelrewiny.github.io/Cafe-/",
    codeUrl: "https://github.com/MohamedElrewiny/Cafe-?tab=readme-ov-file",
  },
  {
    id: 14,
    title: "2rings",
    description: "2rings for Testing.",
    image: "/css/2rings.PNG",
    technologies: ["HTML5", "CSS3"],
    demoUrl: "https://mohamedelrewiny.github.io/2Rings/",
    codeUrl: "https://github.com/MohamedElrewiny/2Rings?tab=readme-ov-file",
  },
];
