import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weights: ["400", "500", "600", "700", "800"]
});


export const metadata = {
  title: "Mohamed Morad | Frontend Developer",
  description: "Generated by Mohamed Morad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
